### ISSUE TITLE
Can't debug it

### ISSUE THREAD

**Issue by mafiaWolf** [foxdog-studios/peepers#2]
I use Android Studio and import your code then debug...
It said: :app:dexDebug concerned with java.. and i dont know how to fix it..please help!

**Comment by dj-foxxy** [comment]
Have a look at the README.md. There's a link to a fork that's already been ported to Android Studio. Give that a try.

**Comment by mafiaWolf** [comment]
Thanks for your reply ^^!
I just solved this problem by 'restart'  :v: (Maybe there is problem with Java at this time)
And, thanks for sharing your code
