### ISSUE TITLE
how to increase quality video in your app?

### ISSUE THREAD

**Issue by stackprogramer** [foxdog-studios/peepers#3]
hi your app is great,how to increase quality video in your app?

**Comment by eldog** [comment]
It depends on the quality of the jpeg, the resolution of the captured image and the CPU time it takes time your phone to compress the jpeg (which decides the framerate). Video encoding (h264 etc) would no doubt work better (but be more complicated, add frames of latency, but reduce bandwidth, everything is trade off) but that work is outside the scope of this project.
