### ISSUE TITLE
MJPEG stream is pausing after some time for few seconds

### ISSUE THREAD

**Issue by parthmshukla** [foxdog-studios/peepers#5]
Hi,

It's working nicely. Can you suggest me what I can do to improve MJpegHttpStereamer performance?

**Comment by parthmshukla** [comment]
I have seen that It was pausing on the Chrome Desktop browser. It is not pausing on Android Chrome web browser.

**Comment by eldog** [comment]
MJPEG in browsers is a black box, with no real tweakable parameters. As it will be transferred over TCP, therefore every packet must be processed in order, it will most likely pause occasionally as a missed frame is resent or delayed. Consider WebRTC for smoother playback, or implementing your own client side buffer.
