### ISSUE TITLE
Rotating image before sending it?

### ISSUE THREAD

**Issue by emrekilic** [foxdog-studios/peepers#7]
Hello,
The camera of too many devices is physically rotated 90 degrees. 
Do you have any suggestions for rotating 90 degrees before sending images?

Regards.

**Comment by dj-foxxy** [comment]
Hi there,

Just had a poke through the code. Looks like [here](https://github.com/foxdog-studios/peepers/blob/master/src/com/foxdogstudios/peepers/CameraStreamer.java#L300) is a good place to rotate the image. I've cut a bit out here:

```Java
// Create JPEG
final YuvImage image = new YuvImage(data, mPreviewFormat, mPreviewWidth, mPreviewHeight,
        null /* strides */);
```
At this point, you've got the width, height, and channels, so you should be able flip it just before creating the `YuvImage`

**Comment by emrekilic** [comment]
Hi @dj-foxxy 
As you suggest, i rotated image before creating yuvimage. However, fps dropped 30 percent. So i decided to turn image on client side.
Thanks for answer.
Regards.

**Comment by dj-foxxy** [comment]
Cool, closing.
